FROM fuzzers/atheris:2.0.7-python3.9

RUN apt-get update

ADD . /src
WORKDIR /src

# ADD fuzz_pybase64.py /fuzz_pybase64.py

RUN pip install pybase64

HEALTHCHECK CMD curl --fail http://localhost:8080/ || exit 1
# RUN chmod +x /src/mayhem/fuzz_pybase64.py

# CMD ["/src/mayhem/fuzz_pybase64.py"]