# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autoupdate_schedule: monthly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-builtin-literals
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: c59bba8fb259db0fec2bbb77ad8ba51ea7341b56  # frozen: v0.15.20
  hooks:
  - id: ruff-check
    args: ["--fix", "--show-fixes"]
  - id: ruff-format

- repo: local
  hooks:
  - id: mypy
    name: mypy 3.9
    entry: mypy
    language: python
    language_version: "3.12"
    stages: [manual]
    'types_or': [ python, pyi ]
    exclude: docs|tools|noxfile.py
    args: ["--python-version=3.9"]
    additional_dependencies:
      - mypy==1.20.2
      - pytest<9
      - types-setuptools

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: d2823d321df3af8f878f7ee3414dc94d037145b9  # frozen: v2.1.0
  hooks:
  - id: mypy
    name: mypy 3.10
    exclude: docs|tools
    args: ["--python-version=3.10"]
    additional_dependencies:
      - nox
      - pytest
      - types-setuptools
  - id: mypy
    name: mypy 3.14
    exclude: docs
    args: ["--python-version=3.14"]
    additional_dependencies:
      - nox
      - pytest
      - types-setuptools

- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: e3eebf65325ccc992422292cb7a4baee967cf815  # frozen: v1.26.1
  hooks:
  - id: zizmor
