# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autoupdate_schedule: monthly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-builtin-literals
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: trailing-whitespace

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.9
  hooks:
  - id: ruff-check
    args: ["--fix", "--show-fixes"]
  - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.20.0
  hooks:
  - id: mypy
    name: mypy 3.9
    exclude: docs|tools|conftest.py
    args: ["--python-version=3.9"]
    additional_dependencies:
      - nox
      - pytest<9
      - types-setuptools
  - id: mypy
    name: mypy 3.10
    exclude: docs|tools|conftest.py
    args: ["--python-version=3.10"]
    additional_dependencies:
      - nox
      - pytest
      - types-setuptools
  - id: mypy
    name: mypy 3.14
    exclude: docs|conftest.py
    args: ["--python-version=3.14"]
    additional_dependencies:
      - nox
      - pytest
      - types-setuptools

- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: v1.23.1
  hooks:
  - id: zizmor
