name: Setup uv & nox
description: Setup uv & nox

runs:
  using: "composite"
  steps:
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          activate-environment: true
          python-version: "3.12"
      - name: Install nox
        run: uv sync --frozen --only-group nox
        shell: bash
