name: Setup uv & nox
description: Setup uv & nox

runs:
  using: "composite"
  steps:
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          activate-environment: true
          python-version: "3.12"
      - name: Install nox
        run: uv sync --frozen --only-group nox
        shell: bash
