name: Build and upload to PyPI

on:
  push:
    tags:
      - '**'
    branches-ignore:
      - "dependabot/**"
  pull_request:

jobs:
  build-wasm-emscripten:
    name: Pyodide wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-13, macos-14 ]
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pyodide-build
        run: pip install pyodide-build==0.26.0

      - name: Compute emsdk version
        id: compute-emsdk-version
        run: |
          # Prepare xbuild environment (side-effect)
          pyodide config list
          # Save EMSDK version
          EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version)
          echo "emsdk-version=$EMSCRIPTEN_VERSION" >> $GITHUB_OUTPUT

      - uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ steps.compute-emsdk-version.outputs.emsdk-version }}
          actions-cache-folder: emsdk-cache

      - name: Build
        run: pyodide build

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Pyodide virtual environment
        run: |
          pyodide venv .venv-pyodide
          cat .venv-pyodide/bin/pip
          .venv-pyodide/bin/pip install -r requirements-test.txt $(echo -n dist/*.whl)

      - name: Test
        run: |
          ls -al .venv-pyodide/bin/
          cat .venv-pyodide/bin/pybase64
          cat .venv-pyodide/bin/pytest
          .venv-pyodide/bin/pybase64 --help
          .venv-pyodide/bin/pytest ./tests
