name: Sanitizers

on:
  push:
    branches:
      - main
      - master
      - "temp/**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  asan:
    name: ASan
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false
      - name: Set up pyenv
        run: |
          git clone https://github.com/pyenv/pyenv.git "$HOME/.pyenv"
          PYENV_ROOT="$HOME/.pyenv"
          PYENV_BIN="$PYENV_ROOT/bin"
          PYENV_SHIMS="$PYENV_ROOT/shims"
          echo "$PYENV_BIN" >> $GITHUB_PATH
          echo "$PYENV_SHIMS" >> $GITHUB_PATH
          echo "PYENV_ROOT=$PYENV_ROOT" >> $GITHUB_ENV
      - name: Check pyenv is working
        run: pyenv --version
      - name: Install python build dependencies
        run: |
          sudo apt-get update
          sudo apt-get -yq install \
            libb2-dev \
            libbz2-dev \
            libffi-dev \
            libgdbm-dev \
            libgdbm-compat-dev \
            liblzma-dev \
            libncurses5-dev \
            libreadline6-dev \
            libsqlite3-dev \
            libssl-dev \
            libzstd-dev \
            lzma-dev \
            tk-dev \
            uuid-dev \
            zlib1g-dev
      - name: Build Python with address sanitizer
        run: |
          CONFIGURE_OPTS="--with-address-sanitizer" pyenv install 3.14
          pyenv global 3.14
      - name: Install dependencies
        run: |
          set -exuo pipefail
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --group test
      - name: Run tests
        run: |
          set -exuo pipefail
          export ASAN_OPTIONS="detect_leaks=1:symbolize=1:allocator_may_return_null=1"
          CFLAGS="-O0 -fsanitize=address -fno-omit-frame-pointer" CIBUILDWHEEL=1 python -m pip install -e .
          python -m pytest

  valgrind:
    name: Valgrind
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false
      - name: Install dependencies
        run: |
          set -exuo pipefail
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends valgrind python3.12-dbg python3.12-dev
          python3.12-dbg -mvenv ./venv-dbg
          ln -sf $(pwd)/venv-dbg/bin/python /usr/local/bin/python-pb64
          python-pb64 -m pip install --upgrade pip setuptools wheel
          python-pb64 -m pip install --group test
      - name: Run valgrind tests
        run: |
          set -exuo pipefail
          CFLAGS="-O0 -g" CIBUILDWHEEL=1 python-pb64 -m pip install -e .
          PYTHONMALLOC=malloc valgrind --leak-check=full --show-leak-kinds=definite --errors-for-leak-kinds=definite --error-exitcode=2 $(which python-pb64) -m pytest

  check_sanitizers:
    if: always()
    name: Check sanitizers
    needs: [asan, valgrind]
    runs-on: ubuntu-slim
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
