name: Test

on:
  push:
    branches:
      - main
      - master
      - "temp/**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        persist-credentials: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: |
          pypy3.9
          pypy3.10
          pypy3.11
          3.9
          3.10
          3.11
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
      with:
        activate-environment: true
        python-version: "3.12"
    - name: Install nox
      run: uv sync --frozen --only-group nox
    - name: Run tests
      run: |
        nox -s test
        nox -s test_parallel
