name: Test

on:
  push:
    branches:
      - main
      - master
      - "temp/**"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-26.04
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        submodules: recursive
        persist-credentials: false
    - name: Setup uv & nox
      uses: ./.github/actions/setup-uv-nox
    - name: Run tests
      run: |
        nox -s test
        nox -s test_parallel
